### ISSUE TITLE
"Keywords" Page YAML Attribute

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/conserving-canvas#19]
A number of the essays (but not all) include the attribute of "keywords" in the page YAML.

Example: 
```
label: "1"
title: "Understanding Structure, Changing Practice"
short_title:
layout: essay
order: 10
contributor:
  - first_name: "Stephen"
    last_name: "Hackney"
    title: "Head of Conservation Science (retired)"
    affiliation: "Tate, London"
keywords: "structure, canvas, ground, painting, oil, lining, research, aging, mechanical, stress, strain, relaxation, chemical, hydrolysis, acidity, pH, efflorescence, air exchange rate, collections care, treatment, deterioration"
abstract: "In the latter part of the twentieth century, conservators questioned the practice of lining paintings on canvas. This inspired fundamental scientific studies of the structure, material, and aging of paintings. The implications of mechanical and chemical aging can now be better predicted. This knowledge has provided conservators with a wide choice of alternative treatments, and it supports the concept of collections care."
---
```

This can be found in essays: 1, 7, 9, 10, 11, 12, 18, 19, 22, 26, 29, 47, 49, 53, 55, 57, 59,
