### ISSUE TITLE
Atlas image viewer shows black background color on inline images in some cases

### ISSUE THREAD

**Issue by geealbers** [thegetty/conserving-canvas#40]
<img width="904" alt="Screen Shot 2022-11-01 at 11 10 57 AM" src="https://user-images.githubusercontent.com/7796401/199307958-a7f22450-c561-4dad-b228-e282eab77937.png">

The black line between the image and the caption in the screenshot above is because the `atlas` web component has a black background color assigned for some reason and perhaps also because the image height is being calculated at not a full pixel dimension:

```css
element {
  width: 640px;
  height: 908.712px;
}
.atlas {
  background: var(--atlas-background, #000);
}
```
Screenshot from Firefox, view at https://first-pages--conserving-canvas.netlify.app/8-posters/51/#fig-51-5

It can be fixed by re-defining the variable in the project's custom.css file, but seems like users shouldn't have to do this.

```css
:root {
  --atlas-background: transparent;
}
```
