### ISSUE TITLE
Need to be able to process shortcodes in figure captions and tables

### ISSUE THREAD

**Issue by geealbers** [thegetty/conserving-canvas#48]
Especially for `% cite %` shortcodes, which are currently marked with double brackets as in the examples below.

```yaml
  - id: "fig-1-2"
    src: "figures/fig-1-2.png"
    zoom: true
    label: "Figure 1.2"
    caption: "Long-term relaxation for several canvases and linings plotted logarithmically against time (from [[Daly Hartin et al. 2011]])."
    credit: "Image: Debra Daly Hartin, Eric Hagan, Stefan Michalski, and Mylène Choquette"

  - id: "fig-1-3"
    src: "figures/fig-1-3.png"
    zoom: true
    label: "Figure 1.3"
    caption: "Strain variations near the canvas edges associated with the use of tacks for attachment to the stretcher (from [[Young and Hibberd 1999]])."
    credit: "Image: Christina R. T. Young and Roger D. Hibberd"
```
